### ISSUE TITLE
JAVA_HOME not set

### ISSUE THREAD

**Issue by hackel** [jan-molak/serenity-cli-node#1]
I installed serenity-cli following the From Scripts to Serenity guide. (All of which are excellent, by the way, thank you!)  It complained about JAVA_HOME not being set:
```
$ serenity run;
error: Did you set JAVA_HOME correctly? $JAVA_HOME not found
error: Did you set JAVA_HOME correctly? $JAVA_HOME not found
(node:22826) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property '0' of undefined
(node:22826) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: Did you set JAVA_HOME correctly? $JAVA_HOME not found
```
It looks like you're using the java-home package which doesn't bother actually trying to figure out the path if the environment variable isn't already set.  (See xudafeng/java-home#4)

As far as I can tell, there's no actual dependency on the JAVA_HOME environment variable.  It doesn't need to be used at all.  Simply running `java -jar serenity-cli.jar` works just fine and generates the reports.  You could allow the path to be overridden, but /usr/bin/java should be a pretty safe bet.

**Comment by jan-molak** [comment]
You're welcome, glad that you found them useful :-)

RE: `java-home` - that's disappointing :/ I agree, `node-which` seems like a better way forward since it's only the `java` binary we're after and as long as it's on the `PATH`, we should be good.
I don't think a scenario where someone has `JAVA_HOME` defined but lacks `java` bin on their `PATH` is likely.

Would you be happy to submit a pull request?

**Comment by hackel** [comment]
I started working on this, and then realised I have no clue if this will actually work on Windows.  The actual change is simple:
```js
// src/commands/run.ts
`const findJava = () => ensureFileIsPresent(which.sync(javaFor(os.type())));`
```
This works fine on my Linux system.  When I started looking into the specs, though, I realized Windows might still need to use JAVA_HOME.  I have no idea if installing Java on Windows automatically modifies the path.

**Comment by nbarrett** [comment]
Actually I've just re-installed my mac tonight from scratch (an unwelcome intrusion bought on by a failed upgrade to sierra 😠) and now I'm also having trouble with the built-in reporting in that I also get `error: Did you set JAVA_HOME correctly? $JAVA_HOME is not set`, whereas `java -jar node_modules/serenity-cli/.cache/serenity-cli-0.0.1-rc.3-all.jar` works fine. I did register my JVM by using jenv however so I wonder whether this is my [not quite configuring jenv](https://github.com/gcuisinier/jenv/issues/123) properly? If this is still an issue, I don't mind having a stab at a PR?

**Comment by jan-molak** [comment]
Hey Nick! It should find Java binary as long as it's on the PATH. I've stopped using JEnv in favour of Marco's excellent [SDKMan](http://sdkman.io), so maybe give that a try?

**Comment by nbarrett** [comment]
Brilliant jan! I've just switched to sdkman and all is well:

`info: Using Java at: /Users/nick/.sdkman/candidates/java/8u131-zulu/bin/java`

Didn't realise sdk supported java as well but since it does, it's now my one-stop-shop 😄

**Comment by jan-molak** [comment]
Yup, @marc0der has done an awesome job, like always :-)

**Comment by rakeshnambiar** [comment]
@jan-molak I end up with the same issue in docker. Please help.

**Comment by rakeshnambiar** [comment]
Hi I have solved it with java-node combined docker image

**Comment by jan-molak** [comment]
Awesome, @rakeshnambiar! Thanks for letting me know :-)

**Comment by paolocarrasco** [comment]
@rakeshnambiar could you share which java-node docker image you used?

**Comment by rakeshnambiar** [comment]
@paolocarrasco I am using timbru31/java-node:8
