### ISSUE TITLE
Error for Java 7 should be Java 8

### ISSUE THREAD

**Issue by matt-blanchette** [jan-molak/serenity-cli-node#11]
error: Looks like you're using an old version of Java? Serenity BDD needs Java 7 or newer.

As of serenity-cli 1.2.4, the requirement is now Java 8 not Java 7:
https://github.com/serenity-bdd/serenity-cli/commit/7772af285bc9974dfbb7a68c3fcce3fcb9309f24

**Comment by jan-molak** [comment]
Thanks, well spotted @matt-blanchette!
