### ISSUE TITLE
403 for serenity-cli-jar

### ISSUE THREAD

**Issue by herebebogans** [jan-molak/serenity-cli-node#14]
The bintray download location for the serenity jar is currently returning a 403.

```
$ yarn serenity update
info: Looks like you need the latest Serenity BDD CLI jar. Let me download it for you...
error: Looks like an error occurred downloading the Serenity BDD CLI jar. 403

$ curl https://dl.bintray.com/serenity/maven/net/serenity-bdd/serenity-cli/1.8.0/serenity-cli-1.8.0-all.jar
Forbidden!
```

A desirable feature might be to download this from a private maven repo eg Artifactory?

Also the return code for `serenity update` should possibly be non zero for a failed download.

**Comment by jan-molak** [comment]
Thanks for spotting that, @herebebogans! Looks like we might be hitting download limits on bintray. We're in contact with tech support so hope to get this resolved soon.

In the meantime you can configure serenity-cli to pull the jar from a different location:

```
serenity update --repository=https://yourcompany.com/maven/ 
```

If your Artifactory uses self-signed certificates you can also add `--ignoreSSL`

**Comment by herebebogans** [comment]
Thanks!

**Comment by asnov** [comment]
Hi @jan-molak , 6 weeks later I have the same error.
It is a first week when I am implementing Serenity-js in a new project so it doesn't look good to start working with Serenity this way. Could you do something about it?

P.S. This is a closed issue so I am not sure that you will receive my writing. Could you acknowledge it, please?

Thank you!
