### ISSUE TITLE
Support for any cucumber.js reports JSON

### ISSUE THREAD

**Issue by mrj04** [jan-molak/serenity-cli-node#19]
arn: net.thucydides.core.reports.json.JSONTestOutcomeReporter - This file was not a valid JSON Serenity test report: reports.json
warn: net.thucydides.core.reports.json.JSONTestOutcomeReporter - This file was not a valid JSON Serenity test report: reports.json

**Comment by jan-molak** [comment]
Hi @mrj04, could you please elaborate a bit more on what kind of support you have in mind? It's quite difficult to tell based on this ticket alone I'm afraid.

**Comment by mrj04** [comment]
@jan-molak 
I wanted to convert the regular cucumber reports to serenity-reports?

**Comment by jan-molak** [comment]
Hey @mrj04 - Serenity/JS acts as a test listener and captures information about your tests as they're executed and uses Serenity BDD CLI to also parse the feature files to gather additional metadata.
Parsing an existing `cucumber.json` report is not supported as it doesn't contain enough information for a Serenity report to be produced I'm afraid.

I'd suggest registering Serenity/JS as a test listener instead; here are examples of how this can be achieved with [plain Cucumber](https://github.com/jan-molak/serenity-js/tree/2.0/examples/cucumber-reporting) as well as [Protractor/Cucumber](https://github.com/jan-molak/serenity-js/tree/2.0/examples/protractor-cucumber).

Does this help?

**Comment by mrj04** [comment]
thanks for the update @jan-molak
